const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const root = require('node:path').resolve(__dirname, '..');
const ts = require(root + '/node_modules/typescript');
const text = fs.readFileSync(root + '/src/services/weatherCache.ts', 'utf8');
let saved = '[]';
const storage = {getItem: () => saved, setItem: (_, value) => {saved = value}};
const context = {exports: {}, localStorage: storage};
vm.runInNewContext(ts.transpileModule(text, {compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText, context);
const cache = context.exports;
const entry = i => ({query:'City '+i, savedAt:12345, weather:{location:'City '+i, country:'SA', temperature:20, humidity:50, windSpeed:10, feelsLike:21, condition:'Sunny'}, hourly:[{time:'12:00', temperature:20, condition:'Sunny'}], daily:[]});
assert.equal(cache.readWeatherCache().length, 0);
saved = '{broken'; assert.equal(cache.readWeatherCache().length, 0);
saved = '[null,{}, {"weather":{}}]'; assert.equal(cache.readWeatherCache().length, 0);
saved = '[]'; for (let i=0; i<25; i++) assert.ok(cache.saveWeatherCache(entry(i)));
assert.equal(cache.readWeatherCache().length, 20);
assert.equal(cache.findCachedWeather(' CITY 24 ').savedAt, 12345);
assert.equal(cache.findCachedWeather('City 24, SA').query, 'City 24');
assert.equal(cache.findCachedWeather('City 0'), undefined);
cache.saveWeatherCache(entry(10)); assert.equal(cache.readWeatherCache()[0].query, 'City 10');
assert.equal(cache.readWeatherCache().length, 20);
storage.setItem = () => {throw new Error('quota')}; assert.equal(cache.saveWeatherCache(entry(50)), false);
storage.getItem = () => {throw new Error('blocked')}; assert.equal(cache.readWeatherCache().length, 0);
console.log('PASS: corrupt/blocked storage, validation, limit, case-insensitive lookup, timestamp, selection order, quota failure.');
